// dao/serverSqlMapping.js
// CRUD SQL语句

var server = {
    insert: 'INSERT INTO server(server_id,server_name,server_app_id,server_ext) VALUES(0,?,?,?)',
    insertIP:'INSERT INTO address_pool(add_id,add_ip,add_pooltype,add_status,) VALUES(0,add_ip,add_pooltype)',
    queryByAppID:'select app_name from application where app_id=?',
    delete:'update server set server_status="0" where server_id=?',        
    queryByAppName: 'select * from application where app_name=?',    
    queryByManagerName: 'select * from application where app_manager_name=?',
    queryAll: 'SELECT server.server_id,server.server_name,GROUP_CONCAT(a.add_pooltype) AS pooltype,GROUP_CONCAT(a.add_ip) AS ip,application.app_name,any_value(a.mainFW) AS mainFW,any_value(firewall.fw_name) AS backFW,host.host_ip,server.server_ext FROM(SELECT firewall.fw_name AS mainFW,address_pool.add_fw_backup_id AS backupFWId,address_pool.add_pooltype,address_pool.add_ip,address_pool.add_server_id,firewall.fw_id FROM address_pool,firewall WHERE address_pool.add_fw_main_id = firewall.fw_id) AS a,firewall,server,host,application WHERE (a.backupFWId = firewall.fw_id AND server.server_host_id = host.host_id AND server.server_id = a.add_server_id AND application.app_id = server.server_app_id AND server.server_status="1")GROUP BY server_id',
    queryByServerID: 'SELECT server.server_id,server.server_name,GROUP_CONCAT(a.add_pooltype) AS pooltype,GROUP_CONCAT(a.add_ip) AS ip,application.app_name,any_value(a.mainFW) AS mainFW,any_value(firewall.fw_name) AS backFW,host.host_ip,server.server_ext FROM(SELECT firewall.fw_name AS mainFW,address_pool.add_fw_backup_id AS backupFWId,address_pool.add_pooltype,address_pool.add_ip,address_pool.add_server_id,firewall.fw_id FROM address_pool,firewall WHERE address_pool.add_fw_main_id = firewall.fw_id) AS a,firewall,server,host,application WHERE (a.backupFWId = firewall.fw_id AND server.server_host_id = host.host_id AND server.server_id = a.add_server_id AND application.app_id = server.server_app_id AND server.server_status="1" AND server.server_id=?)GROUP BY server_id',
    queryByServerName: 'SELECT server.server_id,server.server_name,GROUP_CONCAT(a.add_pooltype) AS pooltype,GROUP_CONCAT(a.add_ip) AS ip,application.app_name,any_value(a.mainFW) AS mainFW,any_value(firewall.fw_name) AS backFW,host.host_ip,server.server_ext FROM(SELECT firewall.fw_name AS mainFW,address_pool.add_fw_backup_id AS backupFWId,address_pool.add_pooltype,address_pool.add_ip,address_pool.add_server_id,firewall.fw_id FROM address_pool,firewall WHERE address_pool.add_fw_main_id = firewall.fw_id) AS a,firewall,server,host,application WHERE (a.backupFWId = firewall.fw_id AND server.server_host_id = host.host_id AND server.server_id = a.add_server_id AND application.app_id = server.server_app_id AND server.server_status="1" AND server.server_name=?)GROUP BY server_id',
    queryByServerIP: 'SELECT server.server_id,server.server_name,GROUP_CONCAT(a.add_pooltype) AS pooltype,GROUP_CONCAT(a.add_ip) AS ip,application.app_name,any_value(a.mainFW) AS mainFW,any_value(firewall.fw_name) AS backFW,host.host_ip,server.server_ext FROM(SELECT firewall.fw_name AS mainFW,address_pool.add_fw_backup_id AS backupFWId,address_pool.add_pooltype,address_pool.add_ip,address_pool.add_server_id,firewall.fw_id FROM address_pool,firewall WHERE address_pool.add_fw_main_id = firewall.fw_id AND address_pool.add_ip=?) AS a,firewall,server,host,application WHERE (a.backupFWId = firewall.fw_id AND server.server_host_id = host.host_id AND server.server_id = a.add_server_id AND application.app_id = server.server_app_id AND server.server_status="1")GROUP BY server_id',
    queryByApplicationName: 'SELECT server.server_id,server.server_name,GROUP_CONCAT(a.add_pooltype) AS pooltype,GROUP_CONCAT(a.add_ip) AS ip,application.app_name,any_value(a.mainFW) AS mainFW,any_value(firewall.fw_name) AS backFW,host.host_ip,server.server_ext FROM(SELECT firewall.fw_name AS mainFW,address_pool.add_fw_backup_id AS backupFWId,address_pool.add_pooltype,address_pool.add_ip,address_pool.add_server_id,firewall.fw_id FROM address_pool,firewall WHERE address_pool.add_fw_main_id = firewall.fw_id) AS a,firewall,server,host,application WHERE (a.backupFWId = firewall.fw_id AND server.server_host_id = host.host_id AND server.server_id = a.add_server_id AND application.app_id = server.server_app_id AND server.server_status="1" AND application.app_name=?)GROUP BY server_id',
    queryByFirewallName: 'SELECT server.server_id,server.server_name,GROUP_CONCAT(a.add_pooltype) AS pooltype,GROUP_CONCAT(a.add_ip) AS ip,application.app_name,any_value(a.mainFW) AS mainFW,any_value(firewall.fw_name) AS backFW,host.host_ip,server.server_ext FROM(SELECT firewall.fw_name AS mainFW,address_pool.add_fw_backup_id AS backupFWId,address_pool.add_pooltype,address_pool.add_ip,address_pool.add_server_id,firewall.fw_id FROM address_pool,firewall WHERE address_pool.add_fw_main_id = firewall.fw_id AND firewall.fw_name=?) AS a,firewall,server,host,application WHERE (a.backupFWId = firewall.fw_id AND server.server_host_id = host.host_id AND server.server_id = a.add_server_id AND application.app_id = server.server_app_id AND server.server_status="1")GROUP BY server_id',
    queryByHostIP: 'SELECT server.server_id,server.server_name,GROUP_CONCAT(a.add_pooltype) AS pooltype,GROUP_CONCAT(a.add_ip) AS ip,application.app_name,any_value(a.mainFW) AS mainFW,any_value(firewall.fw_name) AS backFW,host.host_ip,server.server_ext FROM(SELECT firewall.fw_name AS mainFW,address_pool.add_fw_backup_id AS backupFWId,address_pool.add_pooltype,address_pool.add_ip,address_pool.add_server_id,firewall.fw_id FROM address_pool,firewall WHERE address_pool.add_fw_main_id = firewall.fw_id) AS a,firewall,server,host,application WHERE (a.backupFWId = firewall.fw_id AND server.server_host_id = host.host_id AND server.server_id = a.add_server_id AND application.app_id = server.server_app_id AND server.server_status="1" AND host_ip =?)GROUP BY server_id',
    update: '',
};

module.exports = server;